apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.asm.alauda.io/v1alpha1",
          "kind": "ServiceMesh",
          "metadata": {
            "name": "servicemesh-sample"
          },
          "spec": {
            "config": "apiVersion: asm.alauda.io/v1alpha1\nkind: ServiceMesh\nmetadata:\n  annotations:\n    asm.cpaas.io/creator: admin\n    asm.cpaas.io/display-name: \"\"\n  labels:\n    asm.cpaas.io/cluster: asm\n  name: asm\n  namespace: cpaas-system\nspec:\n  cluster: asm\n  clusterNodeIps:\n  - 192.168.22.5\n  egress:\n    deployMode: Float\n  elasticsearch:\n    isDefault: true\n    url: http://192.168.22.2:9200\n  externalHost: \"\"\n  globalIngressHost: https://asm-dev.alauda.cn/\n  highAvailability: false\n  ingressHost: \"\"\n  ingressScheme: https\n  ipranges:\n    ranges:\n    - '*'\n  istioSidecar:\n    cpuValue: 50m\n    memoryValue: 64Mi\n  istioSidecarInjectorPolicy: false\n  prometheusURL: http://192.168.22.5:30900\n  registryAddress: 192.168.22.1:60080\n  traceSampling: 100\n",
            "foo": "bar",
            "globalConfig": {
              "caBundle": "",
              "clusterName": "global",
              "serverAddress": "https://192.168.22.1:6443",
              "token": "MWpFN3N4Q2FUWDBzc1VZUGFqSG5mVXNGM2dl"
            },
            "version": "v3.3.0"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: asm-cluster-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ServiceMesh is the Schema for the servicemeshes API
      displayName: Service Mesh
      kind: ServiceMesh
      name: servicemeshes.operator.asm.alauda.io
      version: v1alpha1
  description: asm-cluster-operator desc
  displayName: asm-cluster-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - operator.asm.alauda.io
          resources:
          - servicemeshes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator.asm.alauda.io
          resources:
          - servicemeshes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: asm-cluster-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: controller:latest
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cluster-asm installer
  links:
  - name: Asm Cluster Operator
    url: https://asm-cluster-operator.domain
  maturity: alpha
  provider:
    name: yuanfang@alauda.io
  version: 0.0.1
