apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: asm-cluster-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ServiceMesh is the Schema for the servicemeshes API
      displayName: Service Mesh
      kind: ServiceMesh
      name: servicemeshes.operator.asm.alauda.io
      version: v1alpha1
  description: asm-cluster-operator desc
  displayName: asm-cluster-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cluster-asm installer
  links:
  - name: Asm Cluster Operator
    url: https://asm-cluster-operator.domain
  maturity: alpha
  provider:
    name: yuanfang@alauda.io
  version: 0.0.0
